[package]
name = "pssuspend"
version = "0.1.1"
edition = "2021"

[dependencies]
clap = { version = "4.5.30" }
ntapi = "0.4.1"
winapi = { version = "0.3.9", features = ["processthreadsapi"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
