[package]
name = "pssuspend"
version = "0.1.0"
edition = "2021"

[dependencies]
ntapi = "0.4.1"
winapi = { version = "0.3.9", features = ["processthreadsapi"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
